---
# tasks file for git

- name: Ensure git is installed.
  package:
    name: git
    state: present

- name: Define git user
  set_fact:
    role_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: role_user == ''

- block:
    - name: Set git username
      set_fact:
        git_username: "{{ git_user_email.split('@')[0] }}"

    - name: place git configuration
      template:
        src: gitconfig.j2
        dest: "/home/{{ role_user }}/.gitconfig"
        owner: "{{ role_user }}"
        group: "{{ role_user }}"

    - name: generate ssh key
      command: ssh-keygen -q -t rsa -b 4096 -C {{ git_user_email }} -f /home/{{ role_user }}/.ssh/id_rsa_git
      args:
        creates: /home/{{ role_user }}/.ssh/id_rsa_git
  when:
    - git_user_email is defined
    - '"@" in git_user_email'

